### Introduction to Numpy

In [1]:
import numpy as np

In [2]:
print("numpy version", np.__version__)

numpy version 1.19.2


In [7]:
arr_int = np.array([[1,2,3],[4,5,6]])
print(arr_int)
print( "type:", type(arr_int), "shape:", arr_int.shape)
print("axis 0:", arr_int.shape[0], "axis 1:", arr_int.shape[1])
print(len(arr_int))

[[1 2 3]
 [4 5 6]]
type: <class 'numpy.ndarray'> shape: (2, 3)
axis 0: 2 axis 1: 3
2


In [38]:
arr1d_float = np.array([.1, .2, .3, .4])
print(arr1d_float)
print( "type:", type(arr1d_float), "shape:", arr1d_float.shape)
print("axis 0:", arr1d_float.shape[0])
print(len(arr1d_float))

arr3d_int = np.array([[[1, 2], [3, 4], [.1, .2]], [[5, 6], [7, 8], [.3, .4]]])
print(arr3d_int)
print( "type:", type(arr3d_int), "shape:", arr3d_int.shape)
print(
    "axis 0:", arr3d_int.shape[0],
    "axis 0:", arr3d_int.shape[1],
    "axis 0:", arr3d_int.shape[2]
)
print(len(arr3d_int))

[0.1 0.2 0.3 0.4]
type: <class 'numpy.ndarray'> shape: (4,)
axis 0: 4
4
[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]]

 [[5.  6. ]
  [7.  8. ]
  [0.3 0.4]]]
type: <class 'numpy.ndarray'> shape: (2, 3, 2)
axis 0: 2 axis 0: 3 axis 0: 2
2


In [12]:
arr_zeros = np.zeros((2,3), dtype="int32")
print(arr_zeros, arr_zeros.dtype, type(arr_zeros))

[[0 0 0]
 [0 0 0]] int32 <class 'numpy.ndarray'>


In [13]:
arr_zeros = np.zeros((2,3))
print(arr_zeros, arr_zeros.dtype, type(arr_zeros))

[[0. 0. 0.]
 [0. 0. 0.]] float64 <class 'numpy.ndarray'>


In [14]:
arr_zeros = np.zeros((2,3))
print(arr_zeros, arr_zeros.dtype, type(arr_zeros), arr_zeros.shape)

[[0. 0. 0.]
 [0. 0. 0.]] float64 <class 'numpy.ndarray'> (2, 3)


In [15]:
arr_ones = np.ones((2,4))
print(arr_ones, arr_ones.dtype, type(arr_ones), arr_ones.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64 <class 'numpy.ndarray'> (2, 4)


In [18]:
arr_arange = np.arange(1, 2, .1)
print(arr_arange, arr_arange.dtype, type(arr_arange), arr_arange.shape)

[1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9] float64 <class 'numpy.ndarray'> (10,)


In [26]:
np.empty((100, 100))

array([[7.50846335e-312, 7.50878350e-312, 6.95187041e-310, ...,
                    nan,             nan,             nan],
       [            nan,             nan,             nan, ...,
                    nan,             nan, 6.57017133e-299],
       [            nan, 1.57488147e-301,             nan, ...,
                    nan,             nan,             nan],
       ...,
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000, ...,
        0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [27]:
arr_empty = np.empty((100, 100))
print(arr_empty, arr_empty.dtype, type(arr_empty), arr_empty.shape)

[[7.50846335e-312 7.50878350e-312 2.12199579e-314 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 ...
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
  0.00000000e+000 0.00000000e+000]] float64 <class 'numpy.ndarray'> (100, 100)


In [33]:
dummy_list = [[1,2,3],[4,5,6]]
print("list:", dummy_list)
print("array:", arr_int)

# indexing
print(dummy_list[0][0], dummy_list[0][:2])
print(arr_int[0, 0], arr_int[0, :2])
print(arr_int[::-1])
print(arr_int[::-1, ::-1])

list: [[1, 2, 3], [4, 5, 6]]
array: [[1 2 3]
 [4 5 6]]
1 [1, 2]
1 [1 2]
[[4 5 6]
 [1 2 3]]
[[6 5 4]
 [3 2 1]]


In [39]:
# ndim and size of ndarray
print("num of dimension:", arr_int.ndim)
print("num of dimension:", arr3d_int.ndim)

print("total items:", arr_int.size)
print("total items:", arr3d_int.size)

num of dimension: 2
num of dimension: 3
total items: 6
total items: 12


In [44]:
# flatten
print("before flatten:", arr_int)
print("after flatten:", arr_int.flatten())

before flatten: [[1 2 3]
 [4 5 6]]
after flatten: [1 2 3 4 5 6]


In [48]:
np.array([10, 11, 12]).shape, np.array([[10, 11, 12]]).shape

((3,), (1, 3))

In [60]:
# append, concatenate and delete
print(np.append(arr1d_float, [10, 11, 12]))
print(np.append(arr_int, [[10, 11, 12]], axis=0))
print(np.append(arr_int, [[10], [11]], axis=1))
print(np.append(arr_int, arr_int, axis=0))
print(np.append(arr_int, arr_int, axis=1))

print(np.concatenate([arr_int, arr_int, arr_int], axis=1))
print(np.concatenate([arr_int, arr_int, arr_int], axis=0))
print(np.concatenate([arr_int, arr_ones], axis=1))
#kalo print(np.concatenate([arr_int, arr_ones], axis=0)) tidak bisa, karena beda beda jumlah kolom

[ 0.1  0.2  0.3  0.4 10.  11.  12. ]
[[ 1  2  3]
 [ 4  5  6]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1. 2. 3. 1. 1. 1. 1.]
 [4. 5. 6. 1. 1. 1. 1.]]


In [63]:
print(arr3d_int)
print(np.delete(arr3d_int, 1, axis=0))
print(np.delete(arr3d_int, -1, axis=1))

[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]]

 [[5.  6. ]
  [7.  8. ]
  [0.3 0.4]]]
[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]]]
[[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


In [76]:
# reshape
print(arr3d_int)
print(arr3d_int, arr3d_int.shape)
print(arr3d_int.flatten())
print(np.reshape(arr3d_int, (3, 4)))
print(np.reshape(arr3d_int, (6, 2)), np.reshape(arr3d_int, (6, 2)).ndim)
print(np.reshape(arr3d_int, (6, 1, 2)), np.reshape(arr3d_int, (6, 1, 2)).ndim)
print(np.reshape(arr3d_int, (1, 6, 2)), np.reshape(arr3d_int, (1, 6, 2)).ndim)

print(np.resize(arr3d_int, (5, 2)))
# print(arr3d_int.resize((3, 5)))

[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]]

 [[5.  6. ]
  [7.  8. ]
  [0.3 0.4]]]
[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]]

 [[5.  6. ]
  [7.  8. ]
  [0.3 0.4]]] (2, 3, 2)
[1.  2.  3.  4.  0.1 0.2 5.  6.  7.  8.  0.3 0.4]
[[1.  2.  3.  4. ]
 [0.1 0.2 5.  6. ]
 [7.  8.  0.3 0.4]]
[[1.  2. ]
 [3.  4. ]
 [0.1 0.2]
 [5.  6. ]
 [7.  8. ]
 [0.3 0.4]] 2
[[[1.  2. ]]

 [[3.  4. ]]

 [[0.1 0.2]]

 [[5.  6. ]]

 [[7.  8. ]]

 [[0.3 0.4]]] 3
[[[1.  2. ]
  [3.  4. ]
  [0.1 0.2]
  [5.  6. ]
  [7.  8. ]
  [0.3 0.4]]] 3
[[1.  2. ]
 [3.  4. ]
 [0.1 0.2]
 [5.  6. ]
 [7.  8. ]]


In [82]:
arr1d_float

array([0.1, 0.2, 0.3, 0.4])

In [94]:
print(arr1d_float.shape)

arr2d_float = arr1d_float[:, np.newaxis]
print(arr2d_float, arr2d_float.shape)
print(arr1d_float[None])

print(arr3d_int[:, :, :, np.newaxis].shape)
print(arr3d_int[..., np.newaxis].shape)
print(arr3d_int[:,..., np.newaxis].shape)
print(arr3d_int[:, np.newaxis, ...].shape)

(4,)
[[0.1]
 [0.2]
 [0.3]
 [0.4]] (4, 1)
[[0.1 0.2 0.3 0.4]]
(2, 3, 2, 1)
(2, 3, 2, 1)
(2, 3, 2, 1)
(2, 1, 3, 2)


In [91]:
...

Ellipsis

In [99]:
# transpose 
print(arr_int)
print(arr_int.T)
print(np.transpose(arr_int))
print(np.transpose(arr_int))
print(arr_int.reshape(arr_int.shape[1], arr_int.shape[0]))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 2]
 [3 4]
 [5 6]]


In [114]:
# mathematics operation
print(dummy_list)
print(arr_int)
print(arr1d_float)

print(dummy_list + dummy_list)
print(arr_int + arr_int)
print(arr_int * 10)
print(arr3d_int * 10)
print(arr1d_float * arr1d_float)
print(arr_int * arr_int)
print(arr_int / arr_int)
print(arr_int / 10)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
[0.1 0.2 0.3 0.4]
[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[10 20 30]
 [40 50 60]]
[[[10. 20.]
  [30. 40.]
  [ 1.  2.]]

 [[50. 60.]
  [70. 80.]
  [ 3.  4.]]]
[0.01 0.04 0.09 0.16]
[[ 1  4  9]
 [16 25 36]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [117]:
print(arr_int)
print(arr_int.sum(axis=1))
print(arr_int.sum(axis=0, keepdims=True))
print(arr_int.sum(keepdims=True))

[[1 2 3]
 [4 5 6]]
[ 6 15]
[[5 7 9]]
[[21]]


In [120]:
print(arr1d_float, arr1d_float)
print(np.dot(arr1d_float, arr1d_float))
print(np.dot(arr3d_int, 10))

print(arr_int)
print(np.dot(arr_int, arr_int.T))

[0.1 0.2 0.3 0.4] [0.1 0.2 0.3 0.4]
0.3
[[[10. 20.]
  [30. 40.]
  [ 1.  2.]]

 [[50. 60.]
  [70. 80.]
  [ 3.  4.]]]
[[1 2 3]
 [4 5 6]]
[[14 32]
 [32 77]]


In [125]:
print(arr_int)
print(arr_int.T)
print(np.matmul(arr_int.T, arr_int))
print(np.matmul(arr_int, arr_int.T))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[17 22 27]
 [22 29 36]
 [27 36 45]]
[[14 32]
 [32 77]]


In [124]:
print(np.einsum("ij->ji", arr_int))

[[1 4]
 [2 5]
 [3 6]]


In [135]:
# bilangan random
print(np.random.randint(10, size = (2, 3)))
print(np.random.uniform(10, 10))
print(np.random.randn(10, 10))
print(np.random.normal(1., 10, size=()))

print(np.random.seed(10))

[[4 9 6]
 [4 5 6]]
10.0
[[-1.33704173  0.28957055 -0.27572099 -1.0844576   2.19401887  0.52902068
  -0.61703492  0.54370684  0.95779514  1.19176672]
 [ 1.29174399  0.59531725  0.07063033  0.88610811 -0.08369162  0.12315071
   1.25275474 -0.74540144 -0.15444366 -0.04376346]
 [-0.08769213 -0.27071054  0.82078216 -2.1963146  -0.79907193 -0.23527889
  -1.23496562 -0.39457077  0.854457   -1.32843405]
 [ 0.68067913 -0.49410095  0.01431493 -0.89005776 -0.3267363  -0.02445294
  -0.35008755 -0.16472043  0.9840316   0.74483504]
 [ 0.84502981 -0.56562812 -1.43139136 -0.06885101  0.37315108 -1.08928361
   1.93145965 -0.53213245  1.00267083  1.34309089]
 [-0.24863036  0.12584108 -1.33717594 -1.10926345  2.01412415 -0.64566977
   0.77878836  0.03951558  1.43582731  0.1213632 ]
 [-0.1431113   2.06179579  0.3348868   0.74605759 -0.00873031  0.44596839
  -0.93059165 -0.10804046 -0.1204848  -0.45677366]
 [ 0.64591643  0.94497857  0.70968992 -0.54252942 -0.84399246  0.73393198
  -0.46264193  1.10767428 -

In [136]:
print(np.random.seed(10))

None
